### ISSUE TITLE
Create a Logo for the Org

### ISSUE THREAD

**Issue by shreyateeza** [Novice-Paradigm/Hello-World#2]
- A logo needs to be created for the Novice Paradigm organisation.
- Can be related to the current picture of the organisation.
- Original ideas are most welcome!

**Comment by reshusinghhh** [comment]
I can help with logo design.
Can you give some samples to begin with?

**Comment by shreyateeza** [comment]
@reshusinghhh I want the logo to contain a baby buddha as given in the current profile picture.

**Comment by reshusinghhh** [comment]
![zjhl2lgef9cyrql0jfa7kzbw2vueqbvonxfn0tp9oxde9g5shnn1i bv9ettdv9dsbugw0py](https://user-images.githubusercontent.com/18489140/40474403-8c35c884-5f5c-11e8-8e8e-2b704983163e.png)

How about this way?

**Comment by shreyateeza** [comment]
I wanted a baby buddha's picture. And if possible in pastel shade.

**Comment by shreyateeza** [comment]
See the images used be Free and open. They must not be subject to copyright. So try to make something that has been inspired from these to images and not using them.

**Comment by AmbiTyga** [comment]
I have a logo, but it seems like I don't know how to attach the picture in the comment, kindly help me

**Comment by AmbiTyga** [comment]
![adobe_20180603_235151](https://user-images.githubusercontent.com/39136064/40889840-f727df34-678a-11e8-957b-534b6e24bdcf.png)

How about this

**Comment by shreyateeza** [comment]
@AmbiTyga This is amazing! But in the bottom it has been written that "designed by free---.com" that means that this image is subject to copyright. Please correct me if I am wrong!

>See the images used should be Free and open. They must not be subject to copyright. So try to make something that has been inspired from these images and not using them.

**Comment by AmbiTyga** [comment]
Sorry for that I'll make u a new logo this time myself

**Comment by AmbiTyga** [comment]
![img_20180606_064848](https://user-images.githubusercontent.com/39136064/41010549-d9dd9668-6955-11e8-8f96-4c6551d90189.jpg)

If you want any particular changes in this then notify me ASAP

**Comment by shreyateeza** [comment]
@AmbiTyga Just remove the curly braces from both sides. I think that would do.

**Comment by AmbiTyga** [comment]
![picsart_06-06-09 59 04](https://user-images.githubusercontent.com/39136064/41016981-5a6aaf36-6970-11e8-870a-626926528aa7.jpg)
Here u go

**Comment by adi44** [comment]
If it is not finalized I can help.

**Comment by shreyateeza** [comment]
@AmbiTyga Thank you so much for the picture! :heart_eyes: 
@adi44 You can suggest new ideas that you want to see in this organisation. I think my search is over.

**Comment by shreyateeza** [comment]
@AmbiTyga I have sent you invitation few days ago! Check your mail.

**Comment by nisnt2411** [comment]
if it's not done yet I could help with a fresh logo!

**Comment by shreyateeza** [comment]
@nisnt2411 Please go through the available issues in other repos.
This issue is no longer up for grabs. :slightly_smiling_face:
