### ISSUE TITLE
Insert Emoji at appropriate places in the README.md

### ISSUE THREAD

**Issue by shreyateeza** [Novice-Paradigm/Hello-World#7]
You can use this as reference - https://gist.github.com/rxaviers/7360908

**Comment by rishiip** [comment]
@shreyateeza I can work on it!

Let me know.

**Comment by shreyateeza** [comment]
I have sent you invitation. Please accept it so that I can assign you the issue. :)
Please comment here once you have accepted the invitation.

**Comment by rishiip** [comment]
@shreyateeza I accepted your invitation. You can assign it to me. I seen single PR for this issue. I am able to review it if you allow, and then once it's merged I can send my PR on the top of it if I found any modification.

Do let me know if you have any other approach in your mind.

**Comment by shreyateeza** [comment]
@rishiip I have assigned you. I want you to leave space before the the emoji and in the last line keep only one smiling emoji.
You can also add more emojis if you think it is required anywhere keeping in mind that it shouldn't look like excess of it.

> I seen single PR for this issue. I am able to review it if you allow

You can review any PR you want. No need to ask me. :slightly_smiling_face:

**Comment by shreyateeza** [comment]
Also do mention in your commit message the issue number.

**Comment by rishiip** [comment]
@shreyateeza Sure! :tada:

**Comment by rishiip** [comment]
@shreyateeza 👍

**Comment by rishiip** [comment]
PR #13
